spring:
  application:
    name: itoken-eureka
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.229.137
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: 192.168.229.137:${server.port}/eureka/,http://192.168.229.137:${server.port}/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info